# NHipster ci-cd
machine:
  services:
    - docker
  java:
    version: oraclejdk8
  node:
    version: 14.16.0
dependencies:
  cache_directories:
    - node
    - node_modules
  override:
    - npm install -g npm
    - node -v
    - npm -v
    - npm install
test:
  override:
    - cd server
    - npm install
    - npm test
    - npm run test
    - cd server && npm run build
